
- name: remove old template
  tags: email
  file: path=/tmp/email.txt state=file state=absent
  delegate_to: localhost

- name: template email
  tags: email
  template: src=email_template.j2 dest=/tmp/email.txt
  delegate_to: localhost
  #with_items: "{{ chosen }}"

- name: account creation email
  tags: email
  mail: host='127.0.0.1'
        from={{ from }}
        subject="Your New Account"
        body='{{ lookup("file", "/tmp/email.txt") }}'
        to={{ from }}
        cc={{ to }}
        subtype=html
  when: collab is not defined

- name: collab creation email
  tags: email
  mail: host='127.0.0.1'
        from={{ from }}
        subject="Your New Account"
        body='{{ lookup("file", "/tmp/email.txt") }}'
        to={{ from }}
        cc="{{ email }}"
        subtype=html
  when: collab is defined

- name: slack notification
  tags: email,slack
  slack: token={{ slack_token }} channel=#ansible msg='{{ user }} account created by {{ ansible_env.SUDO_USER }}' color=good
         icon_url=http://media.linkonlineworld.com/img/Large/2014/11/9/2014_11_9_10_22_13_286.jpg
  when: ansible_env.SUDO_USER is defined

- name: slack notification
  tags: email,slack
  slack: token={{ slack_token }} channel=#ansible msg='{{ user }} account created by {{ ansible_env.USER }}' color=good
         icon_url=http://media.linkonlineworld.com/img/Large/2014/11/9/2014_11_9_10_22_13_286.jpg
  when: ansible_env.USER == 'root' and ansible_env.SUDO_USER is not defined
